-- ============================================================
-- seed_rawalpindi_businesses.sql
-- ── DEPRECATED ──────────────────────────────────────────────
--
-- This approach (giant SQL seed file) has been replaced by the
-- reusable Node.js importer at scripts/import-businesses.js
--
-- To seed businesses, use:
--
--   node scripts/import-businesses.js \
--     --file data/rawalpindi.xlsx \
--     --city Rawalpindi \
--     --dry-run        (preview first)
--
--   node scripts/import-businesses.js \
--     --file data/rawalpindi.xlsx \
--     --city Rawalpindi
--
-- The source Excel file is at:
--   /mnt/user-data/uploads/WaitMate_Master_Database.xlsx
-- Copy it to: data/rawalpindi.xlsx
--
-- See scripts/README.md for full documentation.
-- ============================================================
